# Travis integration
language: c

# Container-base architecture
sudo: required

env:
    - OTT_DIR=~/ott ELPI_DIR=~/elpi 

cache:
      directories:
            - $HOME/ott
            - $HOME/elpi

addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-native-compilers
    - ocaml-core
    - menhir
    - coq
    - latexmk
    - texlive-latex-extra
    - latex-xcolor


before_install:

after_success:
    - make doc
