# Travis integration
language: c

# Container-base architecture
sudo: required

env:
  - OTT_DIR=~

addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-native-compilers
    - coq

before_install:

after_success:
    - make doc
